name: Keep VulnEdu Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  ping-health:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping VulnEdu Health Endpoint
        run: |
          echo "🏥 Pinging VulnEdu to keep it awake..."
          
          # Replace YOUR_APP_NAME with your actual Render app name
          HEALTH_URL="https://vulnedu.onrender.com/health"
          
          # Ping the health endpoint
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" "$HEALTH_URL" || echo "HTTPSTATUS:000")
          
          # Extract HTTP status
          http_code=$(echo "$response" | tr -d '\n' | sed -E 's/.*HTTPSTATUS:([0-9]{3})$/\1/')
          
          echo "📊 HTTP Status: $http_code"
          
          # Check if successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ VulnEdu is awake and healthy!"
          else
            echo "❌ Failed to ping VulnEdu (Status: $http_code)"
            exit 1
          fi
      
      - name: Log Timestamp
        run: |
          echo "🕐 Keep-alive completed at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
